//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GUI.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UsuarioCadastrarOperationCompleted;
        
        private System.Threading.SendOrPostCallback UsuarioListarOperationCompleted;
        
        private System.Threading.SendOrPostCallback UsuarioAlterarOperationCompleted;
        
        private System.Threading.SendOrPostCallback UsuarioDeletarOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerfilListarOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerfilCadastrarAlterarOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerfilDeletarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProdutoListarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProdutoCadastrarAlterarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProdutoDeletarOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::GUI.Properties.Settings.Default.GUI_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UsuarioCadastrarCompletedEventHandler UsuarioCadastrarCompleted;
        
        /// <remarks/>
        public event UsuarioListarCompletedEventHandler UsuarioListarCompleted;
        
        /// <remarks/>
        public event UsuarioAlterarCompletedEventHandler UsuarioAlterarCompleted;
        
        /// <remarks/>
        public event UsuarioDeletarCompletedEventHandler UsuarioDeletarCompleted;
        
        /// <remarks/>
        public event PerfilListarCompletedEventHandler PerfilListarCompleted;
        
        /// <remarks/>
        public event PerfilCadastrarAlterarCompletedEventHandler PerfilCadastrarAlterarCompleted;
        
        /// <remarks/>
        public event PerfilDeletarCompletedEventHandler PerfilDeletarCompleted;
        
        /// <remarks/>
        public event ProdutoListarCompletedEventHandler ProdutoListarCompleted;
        
        /// <remarks/>
        public event ProdutoCadastrarAlterarCompletedEventHandler ProdutoCadastrarAlterarCompleted;
        
        /// <remarks/>
        public event ProdutoDeletarCompletedEventHandler ProdutoDeletarCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UsuarioCadastrar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UsuarioCadastrar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("UsuarioCadastrar", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void UsuarioCadastrarAsync(Usuario usuario) {
            this.UsuarioCadastrarAsync(usuario, null);
        }
        
        /// <remarks/>
        public void UsuarioCadastrarAsync(Usuario usuario, object userState) {
            if ((this.UsuarioCadastrarOperationCompleted == null)) {
                this.UsuarioCadastrarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsuarioCadastrarOperationCompleted);
            }
            this.InvokeAsync("UsuarioCadastrar", new object[] {
                        usuario}, this.UsuarioCadastrarOperationCompleted, userState);
        }
        
        private void OnUsuarioCadastrarOperationCompleted(object arg) {
            if ((this.UsuarioCadastrarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UsuarioCadastrarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UsuarioListar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
        public Usuario[] UsuarioListar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            object[] results = this.Invoke("UsuarioListar", new object[] {
                        usuario});
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void UsuarioListarAsync(Usuario usuario) {
            this.UsuarioListarAsync(usuario, null);
        }
        
        /// <remarks/>
        public void UsuarioListarAsync(Usuario usuario, object userState) {
            if ((this.UsuarioListarOperationCompleted == null)) {
                this.UsuarioListarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsuarioListarOperationCompleted);
            }
            this.InvokeAsync("UsuarioListar", new object[] {
                        usuario}, this.UsuarioListarOperationCompleted, userState);
        }
        
        private void OnUsuarioListarOperationCompleted(object arg) {
            if ((this.UsuarioListarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UsuarioListarCompleted(this, new UsuarioListarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UsuarioAlterar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UsuarioAlterar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("UsuarioAlterar", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void UsuarioAlterarAsync(Usuario usuario) {
            this.UsuarioAlterarAsync(usuario, null);
        }
        
        /// <remarks/>
        public void UsuarioAlterarAsync(Usuario usuario, object userState) {
            if ((this.UsuarioAlterarOperationCompleted == null)) {
                this.UsuarioAlterarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsuarioAlterarOperationCompleted);
            }
            this.InvokeAsync("UsuarioAlterar", new object[] {
                        usuario}, this.UsuarioAlterarOperationCompleted, userState);
        }
        
        private void OnUsuarioAlterarOperationCompleted(object arg) {
            if ((this.UsuarioAlterarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UsuarioAlterarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/UsuarioDeletar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UsuarioDeletar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("UsuarioDeletar", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void UsuarioDeletarAsync(Usuario usuario) {
            this.UsuarioDeletarAsync(usuario, null);
        }
        
        /// <remarks/>
        public void UsuarioDeletarAsync(Usuario usuario, object userState) {
            if ((this.UsuarioDeletarOperationCompleted == null)) {
                this.UsuarioDeletarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsuarioDeletarOperationCompleted);
            }
            this.InvokeAsync("UsuarioDeletar", new object[] {
                        usuario}, this.UsuarioDeletarOperationCompleted, userState);
        }
        
        private void OnUsuarioDeletarOperationCompleted(object arg) {
            if ((this.UsuarioDeletarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UsuarioDeletarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PerfilListar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
        public Perfil[] PerfilListar() {
            object[] results = this.Invoke("PerfilListar", new object[0]);
            return ((Perfil[])(results[0]));
        }
        
        /// <remarks/>
        public void PerfilListarAsync() {
            this.PerfilListarAsync(null);
        }
        
        /// <remarks/>
        public void PerfilListarAsync(object userState) {
            if ((this.PerfilListarOperationCompleted == null)) {
                this.PerfilListarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerfilListarOperationCompleted);
            }
            this.InvokeAsync("PerfilListar", new object[0], this.PerfilListarOperationCompleted, userState);
        }
        
        private void OnPerfilListarOperationCompleted(object arg) {
            if ((this.PerfilListarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerfilListarCompleted(this, new PerfilListarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PerfilCadastrarAlterar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PerfilCadastrarAlterar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Perfil perfil) {
            this.Invoke("PerfilCadastrarAlterar", new object[] {
                        perfil});
        }
        
        /// <remarks/>
        public void PerfilCadastrarAlterarAsync(Perfil perfil) {
            this.PerfilCadastrarAlterarAsync(perfil, null);
        }
        
        /// <remarks/>
        public void PerfilCadastrarAlterarAsync(Perfil perfil, object userState) {
            if ((this.PerfilCadastrarAlterarOperationCompleted == null)) {
                this.PerfilCadastrarAlterarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerfilCadastrarAlterarOperationCompleted);
            }
            this.InvokeAsync("PerfilCadastrarAlterar", new object[] {
                        perfil}, this.PerfilCadastrarAlterarOperationCompleted, userState);
        }
        
        private void OnPerfilCadastrarAlterarOperationCompleted(object arg) {
            if ((this.PerfilCadastrarAlterarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerfilCadastrarAlterarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/PerfilDeletar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PerfilDeletar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Perfil perfil) {
            this.Invoke("PerfilDeletar", new object[] {
                        perfil});
        }
        
        /// <remarks/>
        public void PerfilDeletarAsync(Perfil perfil) {
            this.PerfilDeletarAsync(perfil, null);
        }
        
        /// <remarks/>
        public void PerfilDeletarAsync(Perfil perfil, object userState) {
            if ((this.PerfilDeletarOperationCompleted == null)) {
                this.PerfilDeletarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerfilDeletarOperationCompleted);
            }
            this.InvokeAsync("PerfilDeletar", new object[] {
                        perfil}, this.PerfilDeletarOperationCompleted, userState);
        }
        
        private void OnPerfilDeletarOperationCompleted(object arg) {
            if ((this.PerfilDeletarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerfilDeletarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ProdutoListar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
        public Produto[] ProdutoListar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto) {
            object[] results = this.Invoke("ProdutoListar", new object[] {
                        produto});
            return ((Produto[])(results[0]));
        }
        
        /// <remarks/>
        public void ProdutoListarAsync(Produto produto) {
            this.ProdutoListarAsync(produto, null);
        }
        
        /// <remarks/>
        public void ProdutoListarAsync(Produto produto, object userState) {
            if ((this.ProdutoListarOperationCompleted == null)) {
                this.ProdutoListarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProdutoListarOperationCompleted);
            }
            this.InvokeAsync("ProdutoListar", new object[] {
                        produto}, this.ProdutoListarOperationCompleted, userState);
        }
        
        private void OnProdutoListarOperationCompleted(object arg) {
            if ((this.ProdutoListarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProdutoListarCompleted(this, new ProdutoListarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ProdutoCadastrarAlterar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ProdutoCadastrarAlterar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto) {
            this.Invoke("ProdutoCadastrarAlterar", new object[] {
                        produto});
        }
        
        /// <remarks/>
        public void ProdutoCadastrarAlterarAsync(Produto produto) {
            this.ProdutoCadastrarAlterarAsync(produto, null);
        }
        
        /// <remarks/>
        public void ProdutoCadastrarAlterarAsync(Produto produto, object userState) {
            if ((this.ProdutoCadastrarAlterarOperationCompleted == null)) {
                this.ProdutoCadastrarAlterarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProdutoCadastrarAlterarOperationCompleted);
            }
            this.InvokeAsync("ProdutoCadastrarAlterar", new object[] {
                        produto}, this.ProdutoCadastrarAlterarOperationCompleted, userState);
        }
        
        private void OnProdutoCadastrarAlterarOperationCompleted(object arg) {
            if ((this.ProdutoCadastrarAlterarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProdutoCadastrarAlterarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ProdutoDeletar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ProdutoDeletar([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Produto produto) {
            this.Invoke("ProdutoDeletar", new object[] {
                        produto});
        }
        
        /// <remarks/>
        public void ProdutoDeletarAsync(Produto produto) {
            this.ProdutoDeletarAsync(produto, null);
        }
        
        /// <remarks/>
        public void ProdutoDeletarAsync(Produto produto, object userState) {
            if ((this.ProdutoDeletarOperationCompleted == null)) {
                this.ProdutoDeletarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProdutoDeletarOperationCompleted);
            }
            this.InvokeAsync("ProdutoDeletar", new object[] {
                        produto}, this.ProdutoDeletarOperationCompleted, userState);
        }
        
        private void OnProdutoDeletarOperationCompleted(object arg) {
            if ((this.ProdutoDeletarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProdutoDeletarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
    public partial class Usuario {
        
        private string bloqueioField;
        
        private string cpfField;
        
        private int idUsuarioField;
        
        private string loginField;
        
        private string nomeField;
        
        private Perfil perfilField;
        
        private string senhaField;
        
        private Solicitacao[] solicitacoesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bloqueio {
            get {
                return this.bloqueioField;
            }
            set {
                this.bloqueioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Perfil Perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Solicitacao[] Solicitacoes {
            get {
                return this.solicitacoesField;
            }
            set {
                this.solicitacoesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
    public partial class Perfil {
        
        private string descPerfilField;
        
        private int idPerfilField;
        
        private Usuario[] usuariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescPerfil {
            get {
                return this.descPerfilField;
            }
            set {
                this.descPerfilField = value;
            }
        }
        
        /// <remarks/>
        public int IdPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                this.idPerfilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Usuario[] Usuarios {
            get {
                return this.usuariosField;
            }
            set {
                this.usuariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
    public partial class Status {
        
        private string dataStatusField;
        
        private string detalheStatusField;
        
        private Solicitacao solicitacaoField;
        
        private string statusSolicitacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataStatus {
            get {
                return this.dataStatusField;
            }
            set {
                this.dataStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DetalheStatus {
            get {
                return this.detalheStatusField;
            }
            set {
                this.detalheStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Solicitacao Solicitacao {
            get {
                return this.solicitacaoField;
            }
            set {
                this.solicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusSolicitacao {
            get {
                return this.statusSolicitacaoField;
            }
            set {
                this.statusSolicitacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
    public partial class Solicitacao {
        
        private CotacaoDoProduto[] cotacoesProdutosSolicitacoesField;
        
        private string dataPrecisaField;
        
        private string dataSolicitacaoField;
        
        private int idSolicitacaoField;
        
        private string severidadeField;
        
        private Status[] statusField;
        
        private Usuario[] usuariosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CotacaoDoProduto[] CotacoesProdutosSolicitacoes {
            get {
                return this.cotacoesProdutosSolicitacoesField;
            }
            set {
                this.cotacoesProdutosSolicitacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataPrecisa {
            get {
                return this.dataPrecisaField;
            }
            set {
                this.dataPrecisaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataSolicitacao {
            get {
                return this.dataSolicitacaoField;
            }
            set {
                this.dataSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        public int IdSolicitacao {
            get {
                return this.idSolicitacaoField;
            }
            set {
                this.idSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Severidade {
            get {
                return this.severidadeField;
            }
            set {
                this.severidadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Status[] Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Usuario[] Usuarios {
            get {
                return this.usuariosField;
            }
            set {
                this.usuariosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
    public partial class CotacaoDoProduto {
        
        private Cotacao cotacaoField;
        
        private Produto produtoField;
        
        private Solicitacao solicitacaoField;
        
        private double valorCotadoField;
        
        private string venceuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cotacao Cotacao {
            get {
                return this.cotacaoField;
            }
            set {
                this.cotacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Produto Produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Solicitacao Solicitacao {
            get {
                return this.solicitacaoField;
            }
            set {
                this.solicitacaoField = value;
            }
        }
        
        /// <remarks/>
        public double ValorCotado {
            get {
                return this.valorCotadoField;
            }
            set {
                this.valorCotadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Venceu {
            get {
                return this.venceuField;
            }
            set {
                this.venceuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
    public partial class Cotacao {
        
        private CotacaoDoProduto[] cotacaoProdutoSolicitacaoField;
        
        private string dataCotacaoField;
        
        private string dataValidadeCotacaoField;
        
        private int idCotacaoField;
        
        private string statusCotacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CotacaoDoProduto[] CotacaoProdutoSolicitacao {
            get {
                return this.cotacaoProdutoSolicitacaoField;
            }
            set {
                this.cotacaoProdutoSolicitacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataCotacao {
            get {
                return this.dataCotacaoField;
            }
            set {
                this.dataCotacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataValidadeCotacao {
            get {
                return this.dataValidadeCotacaoField;
            }
            set {
                this.dataValidadeCotacaoField = value;
            }
        }
        
        /// <remarks/>
        public int IdCotacao {
            get {
                return this.idCotacaoField;
            }
            set {
                this.idCotacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusCotacao {
            get {
                return this.statusCotacaoField;
            }
            set {
                this.statusCotacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BibliotecaClasses.modelo")]
    public partial class Produto {
        
        private CotacaoDoProduto[] cotacoesProdutosSolicitacoesField;
        
        private string dataCadastroField;
        
        private string descProdutoField;
        
        private int idProdutoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CotacaoDoProduto[] CotacoesProdutosSolicitacoes {
            get {
                return this.cotacoesProdutosSolicitacoesField;
            }
            set {
                this.cotacoesProdutosSolicitacoesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DataCadastro {
            get {
                return this.dataCadastroField;
            }
            set {
                this.dataCadastroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DescProduto {
            get {
                return this.descProdutoField;
            }
            set {
                this.descProdutoField = value;
            }
        }
        
        /// <remarks/>
        public int IdProduto {
            get {
                return this.idProdutoField;
            }
            set {
                this.idProdutoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UsuarioCadastrarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UsuarioListarCompletedEventHandler(object sender, UsuarioListarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UsuarioListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UsuarioListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UsuarioAlterarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UsuarioDeletarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PerfilListarCompletedEventHandler(object sender, PerfilListarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerfilListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerfilListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Perfil[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Perfil[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PerfilCadastrarAlterarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void PerfilDeletarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ProdutoListarCompletedEventHandler(object sender, ProdutoListarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProdutoListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProdutoListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Produto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Produto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ProdutoCadastrarAlterarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ProdutoDeletarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591